#!/bin/bash
# Visual-K experiment: LHP-CZSL v1_init_only with sub_meanings whose K per
# primitive is determined by silhouette clustering on CLIP features (not by
# the LLM). Falsifies the variable-K thesis under "correct" K determination.
#
# Pre-reqs (verify before running):
#   - data/sub_meanings_utzap_visualk.json exists
#       (generated by tools/build_visual_k_sub_meanings.py)
#   - The gumbel-softmax fix is in place (model/lhp_czsl.py)
#   - GPU 1 is free
#
# Run with:
#   bash scripts/run_v1_init_only_visualk_utzap_3seeds.sh
set -e
cd /home/student/dongki/LHP-CZSL
PY=/home/student/anaconda3/envs/lhp_czsl/bin/python
TS=$(date +%Y%m%d_%H%M%S)

for SEED in 0 1 2; do
  YML=config/lhp_czsl_v1_init_only_utzap_l14_visualk_seed${SEED}.yml
  LOG=logs/train_v1_init_only_visualk_utzap_seed${SEED}_${TS}.log
  echo "=== [seed=${SEED}] start $(date) -> ${LOG}" | tee -a logs/run_v1_init_only_visualk_utzap_3seeds_${TS}.log
  CUDA_VISIBLE_DEVICES=1 ${PY} train.py --yml_path ${YML} > ${LOG} 2>&1
  echo "=== [seed=${SEED}] end   $(date)" | tee -a logs/run_v1_init_only_visualk_utzap_3seeds_${TS}.log
done

echo "=== ALL SEEDS DONE $(date)" | tee -a logs/run_v1_init_only_visualk_utzap_3seeds_${TS}.log
